DROP FUNCTION objects_smart_fetch(text, text, int, timestamptz, timestamptz, jsonb) CASCADE;
DROP FUNCTION substitute_params(jsonb, jsonb) CASCADE;
DROP FUNCTION objects_normalized_upsert(jsonb) CASCADE;
DROP FUNCTION jsonb_array_to_pg_array(jsonb) CASCADE;
DROP FUNCTION jsonb_array_to_pg_array_of_text(jsonb) CASCADE;
DROP FUNCTION objects_normalize(jsonb) CASCADE;
DROP FUNCTION _objects_normalize_inner(jsonb) CASCADE;
DROP FUNCTION objects_denormalize(jsonb) CASCADE;
DROP FUNCTION objects_denormalize(jsonb, int) CASCADE;
DROP FUNCTION _objects_denormalize_inner(jsonb, int) CASCADE;
DROP FUNCTION objects_denormalize_unlimited(jsonb) CASCADE;
DROP FUNCTION objects_notify() CASCADE;
DROP FUNCTION objects_search(text) CASCADE;
DROP FUNCTION objects_set_tsv() CASCADE;
DROP FUNCTION tsv_from_jsonb(jsonb) CASCADE;
DROP FUNCTION flatten_jsonb(jsonb) CASCADE;
DROP FUNCTION cast_timestamp(data text) CASCADE;
DROP TABLE objects CASCADE;
